### ISSUE TITLE
question

### ISSUE THREAD

**Issue by rhaynes74** [tristone13th/pdf-annotations#1]
Hi folks, I am wondering what sort of annotations can be exported?  Text highlights? rectangular image selections?

**Comment by tristone13th** [comment]
> Hi folks, I am wondering what sort of annotations can be exported? Text highlights? rectangular image selections?

```python
ANNOTATION_SUBTYPES = frozenset(
    {'Text', 'Highlight', 'Squiggly', 'StrikeOut', 'Underline'})
```
These are the annotations currently supported, feel free to check them out and modify them in the source code.
